### ISSUE TITLE
Write summary report for first iteration of project

### ISSUE THREAD

**Issue by WeaponizedPeach** [Liutexus/T120B516_Snake#35]
- [Requirements for report.](https://moodle.ktu.edu/pluginfile.php/323680/mod_resource/content/1/T120B516-DesignPatterns-reikalavimai-projektui-v2020.v04.pdf)
- Add link to .pdf onto this issue and [upload to Moodle.](https://moodle.ktu.edu/mod/assign/view.php?id=233287)

**Comment by vitmed** [comment]
https://ktuedu-my.sharepoint.com/:f:/g/personal/vitmed_ktu_lt/EhwOf00jdNdCmpbJBjeoZY0Btu9ez1eoeKE3IQX_ArsYQg?e=W4FtCl
